version: '3.8'
services:
  webapp:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229" # Expose port for debugging
    command: node --inspect=0.0.0.0:9229 app.js # Enable Node.js debugging
    volumes:
      - ./data:/usr/src/app/data
      - ./uploads:/usr/src/app/uploads
